name: sperro_neu
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

    # Icons
  cupertino_icons: ^1.0.6
  # Splash Screen
  flutter_native_splash: ^2.4.1

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  firebase_app_check: ^0.3.0+4
  firebase_performance: ^0.10.0+4
  # OTP Field Design
  otp_text_field: ^1.1.3
  # Local Storage
  flutter_secure_storage: ^9.2.2

  # Json Lottie Files
  lottie: ^3.1.2
  # Loction
  geolocator: ^9.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  map_launcher: ^3.4.0
  # Log In
  google_sign_in: ^6.2.1
  # Email Validate
  email_validator: ^3.0.0
  # Email Opener (Verify Email Case)
  open_mail_app: ^0.4.5
  # Country Picker (Location)
  csc_picker: ^0.2.6
  # Permission Handler (Location, Files)
  permission_handler: ^11.3.1
  # Caraousel
  carousel_slider: ^4.1.1
  # State Management
  provider: ^6.1.2
  # Image Packages
  image_picker: ^1.1.2
  galleryimage: ^2.0.1
  cached_network_image: ^3.2.1
  # Loader(depriciated)
#  legacy_progress_dialog: ^0.1.2
  # Fonts
  google_fonts: ^6.2.1
  # String Formatter
  intl: ^0.19.0
  # Bottom Nav Bar
  dot_navigation_bar: ^1.0.2

  # Favourite Button
  like_button: ^2.0.5
  url_launcher: ^6.3.0
  search_page: ^2.3.0

  flutter_chat_bubble: ^2.0.2
  custom_pop_up_menu: ^1.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/lottie/

  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-VariableFont_wght.ttf
          weight: 300